(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var k,aa=aa||{},n=this||self;function ba(a,b){a=a.split(".");var c=n;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}function ca(a){if(a&&a!=n)return da(a.document);null===ea&&(ea=da(n.document));return ea}var fa=/^[\w+/_-]+[=]{0,2}$/,ea=null;
function da(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&fa.test(a)?a:""}function p(a,b){a=a.split(".");b=b||n;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b}function q(){}
function ha(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function r(a){var b=ha(a);return"array"==b||"object"==b&&"number"==typeof a.length}function t(a){return"function"==ha(a)}function u(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var ia="closure_uid_"+(1E9*Math.random()>>>0),ja=0;function ka(a,b,c){return a.call.apply(a.bind,arguments)}
function la(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function v(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?v=ka:v=la;return v.apply(null,arguments)}
function ma(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}
function na(a){if(n.execScript)n.execScript(a,"JavaScript");else if(n.eval){if(null==oa)try{n.eval(""),oa=!0}catch(d){oa=!1}if(oa)n.eval(a);else{var b=n.document,c=b.createElement("script");c.type="text/javascript";c.defer=!1;c.appendChild(b.createTextNode(a));b.head.appendChild(c);b.head.removeChild(c)}}else throw Error("goog.globalEval not available");}var oa=null;function w(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a};function x(a){if(Error.captureStackTrace)Error.captureStackTrace(this,x);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}w(x,Error);x.prototype.name="CustomError";var pa;var qa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ra=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},sa=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};function ta(a){a:{var b=ua;for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:"string"===typeof a?a.charAt(b):a[b]}function va(a,b){b=qa(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c}
function wa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function y(){this.l=this.l;this.u=this.u}y.prototype.l=!1;y.prototype.O=function(){this.l||(this.l=!0,this.w())};y.prototype.w=function(){if(this.u)for(;this.u.length;)this.u.shift()()};var xa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},ya=/&/g,za=/</g,Aa=/>/g,Ba=/"/g,Ca=/'/g,Da=/\x00/g,Ea=/[\x00&<>"']/;function Fa(a,b){return a<b?-1:a>b?1:0};var z;a:{var Ga=n.navigator;if(Ga){var Ha=Ga.userAgent;if(Ha){z=Ha;break a}}z=""}function A(a){return-1!=z.indexOf(a)};function Ia(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function Ja(a){var b={},c;for(c in a)b[c]=a[c];return b}var Ka="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function La(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ka.length;f++)c=Ka[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function B(a,b){this.g=a===Ma&&b||"";this.h=Na}B.prototype.ja=!0;B.prototype.fa=function(){return this.g.toString()};function Oa(a){if(a instanceof B&&a.constructor===B&&a.h===Na)return a.g;ha(a);return"type_error:TrustedResourceUrl"}var Na={},Ma={};function Pa(a,b){a.src=Oa(b);(b=ca(a.ownerDocument&&a.ownerDocument.defaultView))&&a.setAttribute("nonce",b)};function Qa(a){Ea.test(a)&&(-1!=a.indexOf("&")&&(a=a.replace(ya,"&amp;")),-1!=a.indexOf("<")&&(a=a.replace(za,"&lt;")),-1!=a.indexOf(">")&&(a=a.replace(Aa,"&gt;")),-1!=a.indexOf('"')&&(a=a.replace(Ba,"&quot;")),-1!=a.indexOf("'")&&(a=a.replace(Ca,"&#39;")),-1!=a.indexOf("\x00")&&(a=a.replace(Da,"&#0;")));return a};function Ra(a){Ra[" "](a);return a}Ra[" "]=q;function Sa(a,b){var c=Ta;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Ua=A("Opera"),C=A("Trident")||A("MSIE"),Va=A("Edge"),Wa=A("Gecko")&&!(-1!=z.toLowerCase().indexOf("webkit")&&!A("Edge"))&&!(A("Trident")||A("MSIE"))&&!A("Edge"),Xa=-1!=z.toLowerCase().indexOf("webkit")&&!A("Edge");function Ya(){var a=n.document;return a?a.documentMode:void 0}var Za;
a:{var $a="",ab=function(){var a=z;if(Wa)return/rv:([^\);]+)(\)|;)/.exec(a);if(Va)return/Edge\/([\d\.]+)/.exec(a);if(C)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Xa)return/WebKit\/(\S+)/.exec(a);if(Ua)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ab&&($a=ab?ab[1]:"");if(C){var bb=Ya();if(null!=bb&&bb>parseFloat($a)){Za=String(bb);break a}}Za=$a}var cb=Za,Ta={};
function db(a){return Sa(a,function(){for(var b=0,c=xa(String(cb)).split("."),d=xa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==g[0].length&&0==h[0].length)break;b=Fa(0==g[1].length?0:parseInt(g[1],10),0==h[1].length?0:parseInt(h[1],10))||Fa(0==g[2].length,0==h[2].length)||Fa(g[2],h[2]);g=g[3];h=h[3]}while(0==b)}return 0<=b})}var eb;
if(n.document&&C){var fb=Ya();eb=fb?fb:parseInt(cb,10)||void 0}else eb=void 0;var gb=eb;try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){}var hb=!C||9<=Number(gb);function ib(a,b){Ia(b,function(c,d){c&&"object"==typeof c&&c.ja&&(c=c.fa());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:jb.hasOwnProperty(d)?a.setAttribute(jb[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var jb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function kb(a,b,c){var d=arguments,e=document,f=String(d[0]),g=d[1];if(!hb&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',Qa(g.name),'"');if(g.type){f.push(' type="',Qa(g.type),'"');var h={};La(h,g);delete h.type;g=h}f.push(">");f=f.join("")}f=D(e,f);g&&("string"===typeof g?f.className=g:Array.isArray(g)?f.className=g.join(" "):ib(f,g));2<d.length&&lb(e,f,d);return f}
function lb(a,b,c){function d(g){g&&b.appendChild("string"===typeof g?a.createTextNode(g):g)}for(var e=2;e<c.length;e++){var f=c[e];!r(f)||u(f)&&0<f.nodeType?d(f):ra(mb(f)?wa(f):f,d)}}function D(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function mb(a){if(a&&"number"==typeof a.length){if(u(a))return"function"==typeof a.item||"string"==typeof a.item;if(t(a))return"function"==typeof a.item}return!1}
function nb(a){this.g=a||n.document||document};function E(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1}E.prototype.h=function(){this.defaultPrevented=!0};function ob(a){pb();return new B(Ma,a)}var pb=q;ba("userfeedback.api.startFeedback",function(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||n,e=d.document,f=a.nonce||ca(d);f&&!a.nonce&&(a.nonce=f);if("help"==a.flow){var g=p("document.location.href",d);!a.helpCenterContext&&g&&(a.helpCenterContext=g.substring(0,1200));g=!0;if(b&&JSON&&JSON.stringify){var h=JSON.stringify(b);(g=1200>=h.length)&&(a.psdJson=h)}g||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.serverUri||"//www.google.com/tools/feedback";if(g=d.GOOGLE_FEEDBACK_START)g.apply(d,
b);else{d=c+"/load.js?";for(var l in a)b=a[l],null==b||u(b)||(d+=encodeURIComponent(l)+"="+encodeURIComponent(b)+"&");a=e?new nb(9==e.nodeType?e:e.ownerDocument||e.document):pa||(pa=new nb);a=D(a.g,"SCRIPT");f&&a.setAttribute("nonce",f);Pa(a,ob(d));e.body.appendChild(a)}});function qb(a){var b=n.onerror,c=!1;Xa&&!db("535.3")&&(c=!c);n.onerror=function(d,e,f,g,h){b&&b(d,e,f,g,h);a({message:d,fileName:e,line:f,lineNumber:f,qa:g,error:h});return c}}
function rb(a){var b=p("window.location.href");null==a&&(a='Unknown Error of type "null/undefined"');if("string"===typeof a)return{message:a,name:"Unknown error",lineNumber:"Not available",fileName:b,stack:"Not available"};var c=!1;try{var d=a.lineNumber||a.line||"Not available"}catch(f){d="Not available",c=!0}try{var e=a.fileName||a.filename||a.sourceURL||n.$googDebugFname||b}catch(f){e="Not available",c=!0}return!c&&a.lineNumber&&a.fileName&&a.stack&&a.message&&a.name?a:(b=a.message,null==b&&(a.constructor&&
a.constructor instanceof Function?(a.constructor.name?b=a.constructor.name:(b=a.constructor,F[b]?b=F[b]:(b=String(b),F[b]||(c=/function\s+([^\(]+)/m.exec(b),F[b]=c?c[1]:"[Anonymous]"),b=F[b])),b='Unknown Error of type "'+b+'"'):b="Unknown Error of unknown type"),{message:b,name:a.name||"UnknownError",lineNumber:d,fileName:e,stack:a.stack||"Not available"})}var F={};function sb(a,b){this.i=a;this.j=b;this.h=0;this.g=null}sb.prototype.get=function(){if(0<this.h){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.i();return a};function tb(a,b){a.j(b);100>a.h&&(a.h++,b.next=a.g,a.g=b)};var ub=[],vb=[],wb=!1;function xb(a){ub[ub.length]=a;if(wb)for(var b=0;b<vb.length;b++)a(v(vb[b].g,vb[b]))};function yb(a){n.setTimeout(function(){throw a;},0)}var zb;
function Ab(){var a=n.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!A("Presto")&&(a=function(){var e=D(document,"IFRAME");e.style.display="none";document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.close();var g="callImmediate"+Math.random(),h="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;e=v(function(l){if(("*"==h||l.origin==h)&&l.data==g)this.port1.onmessage()},this);
f.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(g,h)}}});if("undefined"!==typeof a&&!A("Trident")&&!A("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var e=c.U;c.U=null;e()}};return function(e){d.next={U:e};d=d.next;b.port2.postMessage(0)}}return function(e){n.setTimeout(e,0)}}function Bb(a){return a}xb(function(a){Bb=a});function Cb(){this.h=this.g=null}var Eb=new sb(function(){return new Db},function(a){a.reset()});Cb.prototype.add=function(a,b){var c=Eb.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c};function Fb(){var a=Gb,b=null;a.g&&(b=a.g,a.g=a.g.next,a.g||(a.h=null),b.next=null);return b}function Db(){this.next=this.h=this.g=null}Db.prototype.set=function(a,b){this.g=a;this.h=b;this.next=null};Db.prototype.reset=function(){this.next=this.h=this.g=null};function Hb(a,b){Ib||Jb();Kb||(Ib(),Kb=!0);Gb.add(a,b)}var Ib;function Jb(){if(n.Promise&&n.Promise.resolve){var a=n.Promise.resolve(void 0);Ib=function(){a.then(Lb)}}else Ib=function(){var b=Lb;b=Bb(b);!t(n.setImmediate)||n.Window&&n.Window.prototype&&!A("Edge")&&n.Window.prototype.setImmediate==n.setImmediate?(zb||(zb=Ab()),zb(b)):n.setImmediate(b)}}var Kb=!1,Gb=new Cb;function Lb(){for(var a;a=Fb();){try{a.g.call(a.h)}catch(b){yb(b)}tb(Eb,a)}Kb=!1};function Mb(a){switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:return!0;default:return!1}};function Nb(){}Nb.prototype.h=null;function Ob(a){return a.h||(a.h=a.j())};var Pb;function Qb(){}w(Qb,Nb);Qb.prototype.g=function(){var a=Rb(this);return a?new ActiveXObject(a):new XMLHttpRequest};Qb.prototype.j=function(){var a={};Rb(this)&&(a[0]=!0,a[1]=!0);return a};
function Rb(a){if(!a.i&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.i=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.i}Pb=new Qb;function Sb(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function G(a){this.g=0;this.u=void 0;this.j=this.h=this.i=null;this.l=this.m=!1;if(a!=q)try{var b=this;a.call(void 0,function(c){H(b,2,c)},function(c){H(b,3,c)})}catch(c){H(this,3,c)}}function Tb(){this.next=this.i=this.h=this.j=this.g=null;this.l=!1}Tb.prototype.reset=function(){this.i=this.h=this.j=this.g=null;this.l=!1};var Ub=new sb(function(){return new Tb},function(a){a.reset()});function Vb(a,b,c){var d=Ub.get();d.j=a;d.h=b;d.i=c;return d}
function I(a){if(a instanceof G)return a;var b=new G(q);H(b,2,a);return b}G.prototype.then=function(a,b,c){return Wb(this,t(a)?a:null,t(b)?b:null,c)};G.prototype.$goog_Thenable=!0;function J(a,b){return Wb(a,null,b,void 0)}G.prototype.cancel=function(a){if(0==this.g){var b=new K(a);Hb(function(){Xb(this,b)},this)}};
function Xb(a,b){if(0==a.g)if(a.i){var c=a.i;if(c.h){for(var d=0,e=null,f=null,g=c.h;g&&(g.l||(d++,g.g==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.g&&1==d?Xb(c,b):(f?(d=f,d.next==c.j&&(c.j=d),d.next=d.next.next):Yb(c),Zb(c,e,3,b)))}a.i=null}else H(a,3,b)}function $b(a,b){a.h||2!=a.g&&3!=a.g||ac(a);a.j?a.j.next=b:a.h=b;a.j=b}
function Wb(a,b,c,d){var e=Vb(null,null,null);e.g=new G(function(f,g){e.j=b?function(h){try{var l=b.call(d,h);f(l)}catch(m){g(m)}}:f;e.h=c?function(h){try{var l=c.call(d,h);void 0===l&&h instanceof K?g(h):f(l)}catch(m){g(m)}}:g});e.g.i=a;$b(a,e);return e.g}G.prototype.s=function(a){this.g=0;H(this,2,a)};G.prototype.v=function(a){this.g=0;H(this,3,a)};
function H(a,b,c){if(0==a.g){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.g=1;a:{var d=c,e=a.s,f=a.v;if(d instanceof G){$b(d,Vb(e||q,f||null,a));var g=!0}else if(Sb(d))d.then(e,f,a),g=!0;else{if(u(d))try{var h=d.then;if(t(h)){bc(d,h,e,f,a);g=!0;break a}}catch(l){f.call(a,l);g=!0;break a}g=!1}}g||(a.u=c,a.g=b,a.i=null,ac(a),3!=b||c instanceof K||cc(a,c))}}
function bc(a,b,c,d,e){function f(l){h||(h=!0,d.call(e,l))}function g(l){h||(h=!0,c.call(e,l))}var h=!1;try{b.call(a,g,f)}catch(l){f(l)}}function ac(a){a.m||(a.m=!0,Hb(a.o,a))}function Yb(a){var b=null;a.h&&(b=a.h,a.h=b.next,b.next=null);a.h||(a.j=null);return b}G.prototype.o=function(){for(var a;a=Yb(this);)Zb(this,a,this.g,this.u);this.m=!1};
function Zb(a,b,c,d){if(3==c&&b.h&&!b.l)for(;a&&a.l;a=a.i)a.l=!1;if(b.g)b.g.i=null,dc(b,c,d);else try{b.l?b.j.call(b.i):dc(b,c,d)}catch(e){ec.call(null,e)}tb(Ub,b)}function dc(a,b,c){2==b?a.j.call(a.i,c):a.h&&a.h.call(a.i,c)}function cc(a,b){a.l=!0;Hb(function(){a.l&&ec.call(null,b)})}var ec=yb;function K(a){x.call(this,a)}w(K,x);K.prototype.name="cancel";var fc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function gc(a){a=a.match(fc)[1]||null;!a&&n.self&&n.self.location&&(a=n.self.location.protocol,a=a.substr(0,a.length-1));return a?a.toLowerCase():""}
function hc(a,b){if(!b)return a;var c=a.indexOf("#");0>c&&(c=a.length);var d=a.indexOf("?");if(0>d||d>c){d=c;var e=""}else e=a.substring(d+1,c);a=[a.substr(0,d),e,a.substr(c)];c=a[1];a[1]=b?c?c+"&"+b:b:c;return a[0]+(a[1]?"?"+a[1]:"")+a[2]}function ic(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)ic(a,String(b[d]),c);else null!=b&&c.push(a+(""===b?"":"="+encodeURIComponent(String(b))))}function jc(a,b){var c=[];for(b=b||0;b<a.length;b+=2)ic(a[b],a[b+1],c);return c.join("&")}
function kc(a){var b=[],c;for(c in a)ic(c,a[c],b);return b.join("&")}function lc(a,b){var c=2==arguments.length?jc(arguments[1],0):jc(arguments,1);return hc(a,c)};function mc(a){var b={$:7E3,ba:new nc};return oc(a,b).then(function(c){var d=c.responseText;b&&b.oa&&(c=b.oa,0==d.lastIndexOf(c,0)&&(d=d.substring(c.length)));return JSON.parse(d)})}
function oc(a,b){var c=b||{},d=c.ba?c.ba.g():Pb.g();return J(new G(function(e,f){var g;try{d.open("GET",a,!0)}catch(m){f(new L("Error opening XHR: "+m.message,a,d))}d.onreadystatechange=function(){if(4==d.readyState){n.clearTimeout(g);var m;!(m=Mb(d.status))&&(m=0===d.status)&&(m=gc(a),m=!("http"==m||"https"==m||""==m));m?e(d):f(new pc(d.status,a,d))}};d.onerror=function(){f(new L("Network error",a,d))};if(c.headers)for(var h in c.headers){var l=c.headers[h];null!=l&&d.setRequestHeader(h,l)}c.withCredentials&&
(d.withCredentials=c.withCredentials);c.responseType&&(d.responseType=c.responseType);c.mimeType&&d.overrideMimeType(c.mimeType);0<c.$&&(g=n.setTimeout(function(){d.onreadystatechange=q;d.abort();f(new qc(a,d))},c.$));try{d.send(null)}catch(m){d.onreadystatechange=q,n.clearTimeout(g),f(new L("Error sending XHR: "+m.message,a,d))}}),function(e){e instanceof K&&d.abort();throw e;})}function L(a,b){x.call(this,a+", url="+b);this.url=b}w(L,x);L.prototype.name="XhrError";
function pc(a,b,c){L.call(this,"Request Failed, status="+a,b,c);this.status=a}w(pc,L);pc.prototype.name="XhrHttpError";function qc(a,b){L.call(this,"Request timed out",a,b)}w(qc,L);qc.prototype.name="XhrTimeoutError";function nc(){}w(nc,Nb);nc.prototype.g=function(){var a=new XMLHttpRequest;if("withCredentials"in a)return a;if("undefined"!=typeof XDomainRequest)return new rc;throw Error("Unsupported browser");};nc.prototype.j=function(){return{}};
function rc(){this.g=new XDomainRequest;this.readyState=0;this.onreadystatechange=null;this.responseType=this.responseText="";this.status=-1;this.statusText="";this.g.onload=v(this.ga,this);this.g.onerror=v(this.V,this);this.g.onprogress=v(this.ha,this);this.g.ontimeout=v(this.ia,this)}k=rc.prototype;k.open=function(a,b,c){if(null!=c&&!c)throw Error("Only async requests are supported.");this.g.open(a,b)};
k.send=function(a){if(a)if("string"==typeof a)this.g.send(a);else throw Error("Only string data is supported");else this.g.send()};k.abort=function(){this.g.abort()};k.setRequestHeader=function(){};k.getResponseHeader=function(a){return"content-type"==a.toLowerCase()?this.g.contentType:""};k.ga=function(){this.status=200;this.responseText=this.g.responseText;sc(this,4)};k.V=function(){this.status=500;this.responseText="";sc(this,4)};k.ia=function(){this.V()};
k.ha=function(){this.status=200;sc(this,1)};function sc(a,b){a.readyState=b;if(a.onreadystatechange)a.onreadystatechange()}k.getAllResponseHeaders=function(){return"content-type: "+this.g.contentType};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function M(a){var b=tc;this.l=[];this.A=b;this.B=a||null;this.j=this.g=!1;this.i=void 0;this.s=this.F=this.u=!1;this.m=0;this.h=null;this.o=0}M.prototype.cancel=function(a){if(this.g)this.i instanceof M&&this.i.cancel();else{if(this.h){var b=this.h;delete this.h;a?b.cancel(a):(b.o--,0>=b.o&&b.cancel())}this.A?this.A.call(this.B,this):this.s=!0;this.g||(a=new N(this),uc(this),O(this,!1,a))}};M.prototype.v=function(a,b){this.u=!1;O(this,a,b)};function O(a,b,c){a.g=!0;a.i=c;a.j=!b;vc(a)}
function uc(a){if(a.g){if(!a.s)throw new wc(a);a.s=!1}}M.prototype.callback=function(a){uc(this);O(this,!0,a)};function xc(a,b,c){a.l.push([b,c,void 0]);a.g&&vc(a)}M.prototype.then=function(a,b,c){var d,e,f=new G(function(g,h){d=g;e=h});xc(this,d,function(g){g instanceof N?f.cancel():e(g)});return f.then(a,b,c)};M.prototype.$goog_Thenable=!0;function yc(a){return sa(a.l,function(b){return t(b[1])})}
function vc(a){if(a.m&&a.g&&yc(a)){var b=a.m,c=zc[b];c&&(n.clearTimeout(c.g),delete zc[b]);a.m=0}a.h&&(a.h.o--,delete a.h);b=a.i;for(var d=c=!1;a.l.length&&!a.u;){var e=a.l.shift(),f=e[0],g=e[1];e=e[2];if(f=a.j?g:f)try{var h=f.call(e||a.B,b);void 0!==h&&(a.j=a.j&&(h==b||h instanceof Error),a.i=b=h);if(Sb(b)||"function"===typeof n.Promise&&b instanceof n.Promise)d=!0,a.u=!0}catch(l){b=l,a.j=!0,yc(a)||(c=!0)}}a.i=b;d&&(h=v(a.v,a,!0),d=v(a.v,a,!1),b instanceof M?(xc(b,h,d),b.F=!0):b.then(h,d));c&&(b=
new Ac(b),zc[b.g]=b,a.m=b.g)}function wc(){x.call(this)}w(wc,x);wc.prototype.message="Deferred has already fired";wc.prototype.name="AlreadyCalledError";function N(){x.call(this)}w(N,x);N.prototype.message="Deferred was canceled";N.prototype.name="CanceledError";function Ac(a){this.g=n.setTimeout(v(this.i,this),0);this.h=a}Ac.prototype.i=function(){delete zc[this.g];throw this.h;};var zc={};function Bc(a,b){var c=b||{};b=c.document||document;var d=Oa(a).toString(),e=D(document,"SCRIPT"),f={X:e,I:void 0},g=new M(f),h=null,l=null!=c.timeout?c.timeout:5E3;0<l&&(h=window.setTimeout(function(){Cc(e,!0);var m=new Dc(1,"Timeout reached for loading script "+d);uc(g);O(g,!1,m)},l),f.I=h);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(Cc(e,c.pa||!1,h),g.callback(null))};e.onerror=function(){Cc(e,!0,h);var m=new Dc(0,"Error while loading script "+
d);uc(g);O(g,!1,m)};f=c.attributes||{};La(f,{type:"text/javascript",charset:"UTF-8"});ib(e,f);Pa(e,a);Ec(b).appendChild(e);return g}function Ec(a){var b;return(b=(a||document).getElementsByTagName("HEAD"))&&0!=b.length?b[0]:a.documentElement}function tc(){if(this&&this.X){var a=this.X;a&&"SCRIPT"==a.tagName&&Cc(a,!0,this.I)}}function Cc(a,b,c){null!=c&&n.clearTimeout(c);a.onload=q;a.onerror=q;a.onreadystatechange=q;b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}
function Dc(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);x.call(this,c);this.code=a}w(Dc,x);function Fc(a){a=void 0===a?{}:a;this.useNotifications=a.useNotifications||!1;this.operatorDeferredUrl=a.operatorDeferredUrl;this.alphaTestMode=a.alphaTestMode||!1;this.stagingMode=a.stagingMode||!1;this.rosterId=a.rosterId||"talk_roster";this.feedbackId=a.feedbackId||74772;this.moleVersion=a.moleVersion||void 0;this.moleUrl=a.moleUrl||"https://support.google.com/inapp/rts_frame";this.gstaticBaseUrl=a.gstaticBaseUrl||void 0;this.operatorDeferredBaseUrl=a.operatorDeferredBaseUrl||void 0;this.isRtl=
a.isRtl||void 0;this.forceLeftMoles=a.forceLeftMoles||void 0;this.helpCenterName=a.helpCenterName||null;this.localeName=a.localeName||null;this.document=a.document||document;this.source=a.source||void 0;this.entityId=a.entityId||void 0;this.authUser=a.authUser||void 0;this.appDomain=a.appDomain||void 0;this.apiKey=a.apiKey||void 0;this.hideQueueWidget=a.hideQueueWidget||!1;this.enableMinimizeRestoreKeyboardShortcut=a.enableMinimizeRestoreKeyboardShortcut||!1;this.showSecondsInChatTranscript=a.showSecondsInChatTranscript||
!1;this.experiments=a.experiments||void 0};var Gc=!C||9<=Number(gb),Hc=C&&!db("9"),Ic=function(){if(!n.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{n.addEventListener("test",q,b),n.removeEventListener("test",q,b)}catch(c){}return a}();function P(a,b){E.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.pointerId=0;this.pointerType="";this.i=null;a&&this.init(a,b)}w(P,E);var Jc={2:"touch",3:"pen",4:"mouse"};
P.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;if(b=a.relatedTarget){if(Wa){a:{try{Ra(b.nodeName);var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||
0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Jc[a.pointerType]||"";this.i=a;a.defaultPrevented&&this.h()};
P.prototype.h=function(){P.H.h.call(this);var a=this.i;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Hc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Q="closure_listenable_"+(1E6*Math.random()|0),Kc=0;function Lc(a,b,c,d,e){this.listener=a;this.g=null;this.src=b;this.type=c;this.capture=!!d;this.K=e;this.key=++Kc;this.D=this.J=!1}function Mc(a){a.D=!0;a.listener=null;a.g=null;a.src=null;a.K=null};function Nc(a){this.src=a;this.g={};this.h=0}Nc.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.h++);var g=Oc(a,b,d,e);-1<g?(b=a[g],c||(b.J=!1)):(b=new Lc(b,this.src,f,!!d,e),b.J=c,a.push(b));return b};function Pc(a,b){var c=b.type;c in a.g&&va(a.g[c],b)&&(Mc(b),0==a.g[c].length&&(delete a.g[c],a.h--))}function Oc(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.D&&f.listener==b&&f.capture==!!c&&f.K==d)return e}return-1};var Qc="closure_lm_"+(1E6*Math.random()|0),Sc={},Tc=0;function Uc(a,b,c,d,e){if(d&&d.once)Vc(a,b,c,d,e);else if(Array.isArray(b))for(var f=0;f<b.length;f++)Uc(a,b[f],c,d,e);else c=Wc(c),a&&a[Q]?a.h.add(String(b),c,!1,u(d)?!!d.capture:!!d,e):Xc(a,b,c,!1,d,e)}
function Xc(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=u(e)?!!e.capture:!!e,h=Yc(a);h||(a[Qc]=h=new Nc(a));c=h.add(b,c,d,g,f);if(!c.g){d=Zc();c.g=d;d.src=a;d.listener=c;if(a.addEventListener)Ic||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent($c(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Tc++}}
function Zc(){var a=ad,b=Gc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Vc(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Vc(a,b[f],c,d,e);else c=Wc(c),a&&a[Q]?a.h.add(String(b),c,!0,u(d)?!!d.capture:!!d,e):Xc(a,b,c,!0,d,e)}
function bd(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)bd(a,b[f],c,d,e);else(d=u(d)?!!d.capture:!!d,c=Wc(c),a&&a[Q])?(a=a.h,b=String(b).toString(),b in a.g&&(f=a.g[b],c=Oc(f,c,d,e),-1<c&&(Mc(f[c]),Array.prototype.splice.call(f,c,1),0==f.length&&(delete a.g[b],a.h--)))):a&&(a=Yc(a))&&(b=a.g[b.toString()],a=-1,b&&(a=Oc(b,c,d,e)),(c=-1<a?b[a]:null)&&cd(c))}
function cd(a){if("number"!==typeof a&&a&&!a.D){var b=a.src;if(b&&b[Q])Pc(b.h,a);else{var c=a.type,d=a.g;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent($c(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Tc--;(c=Yc(b))?(Pc(c,a),0==c.h&&(c.src=null,b[Qc]=null)):Mc(a)}}}function $c(a){return a in Sc?Sc[a]:Sc[a]="on"+a}
function dd(a,b,c,d){var e=!0;if(a=Yc(a))if(b=a.g[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.D&&(f=ed(f,d),e=e&&!1!==f)}return e}function ed(a,b){var c=a.listener,d=a.K||a.src;a.J&&cd(a);return c.call(d,b)}
function ad(a,b){if(a.D)return!0;if(!Gc){var c=b||p("window.event");b=new P(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.g;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;0<=e;e--){b.g=c[e];var f=dd(c[e],a,!0,b);d=d&&f}for(e=0;e<c.length;e++)b.g=c[e],f=dd(c[e],a,!1,b),d=d&&f}return d}return ed(a,new P(b,this))}
function Yc(a){a=a[Qc];return a instanceof Nc?a:null}var fd="__closure_events_fn_"+(1E9*Math.random()>>>0);function Wc(a){if(t(a))return a;a[fd]||(a[fd]=function(b){return a.handleEvent(b)});return a[fd]}xb(function(a){ad=a(ad)});function R(){y.call(this);this.h=new Nc(this);this.ca=this;this.L=null}w(R,y);R.prototype[Q]=!0;R.prototype.addEventListener=function(a,b,c,d){Uc(this,a,b,c,d)};R.prototype.removeEventListener=function(a,b,c,d){bd(this,a,b,c,d)};
function S(a,b){var c=a.L;if(c){var d=[];for(var e=1;c;c=c.L)d.push(c),++e}a=a.ca;c=b.type||b;"string"===typeof b?b=new E(b,a):b instanceof E?b.target=b.target||a:(e=b,b=new E(c,a),La(b,e));e=!0;if(d)for(var f=d.length-1;0<=f;f--){var g=b.g=d[f];e=gd(g,c,!0,b)&&e}g=b.g=a;e=gd(g,c,!0,b)&&e;e=gd(g,c,!1,b)&&e;if(d)for(f=0;f<d.length;f++)g=b.g=d[f],e=gd(g,c,!1,b)&&e}
R.prototype.w=function(){R.H.w.call(this);if(this.h){var a=this.h,b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,Mc(d[e]);delete a.g[c];a.h--}}this.L=null};function gd(a,b,c,d){b=a.h.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.D&&g.capture==c){var h=g.listener,l=g.K||g.src;g.J&&Pc(a.h,g);e=!1!==h.call(l,d)&&e}}return e&&!d.defaultPrevented};function hd(a,b,c){if(t(a))c&&(a=v(a,c));else if(a&&"function"==typeof a.handleEvent)a=v(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:n.setTimeout(a,b||0)};var id="StopIteration"in n?n.StopIteration:{message:"StopIteration",stack:""};function jd(){}jd.prototype.next=function(){throw id;};jd.prototype.T=function(){return this};function kd(a,b){this.h={};this.g=[];this.j=this.i=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof kd)for(c=a.C(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}k=kd.prototype;k.G=function(){ld(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.h[this.g[b]]);return a};k.C=function(){ld(this);return this.g.concat()};
function ld(a){if(a.i!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];Object.prototype.hasOwnProperty.call(a.h,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.i!=a.g.length){var e={};for(c=b=0;b<a.g.length;)d=a.g[b],Object.prototype.hasOwnProperty.call(e,d)||(a.g[c++]=d,e[d]=1),b++;a.g.length=c}}k.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.h,a)?this.h[a]:b};k.set=function(a,b){Object.prototype.hasOwnProperty.call(this.h,a)||(this.i++,this.g.push(a),this.j++);this.h[a]=b};
k.forEach=function(a,b){for(var c=this.C(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};k.T=function(a){ld(this);var b=0,c=this.j,d=this,e=new jd;e.next=function(){if(c!=d.j)throw Error("The map has changed since the iterator was created");if(b>=d.g.length)throw id;var f=d.g[b++];return a?f:d.h[f]};return e};function md(a){if(a.G&&"function"==typeof a.G)return a.G();if("string"===typeof a)return a.split("");if(r(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function nd(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(r(a)||"string"===typeof a)ra(a,b,void 0);else{if(a.C&&"function"==typeof a.C)var c=a.C();else if(a.G&&"function"==typeof a.G)c=void 0;else if(r(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else for(e in c=[],d=0,a)c[d++]=e;d=md(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};function od(a){this.g=a instanceof Fc?a:new Fc(a);this.g=pd(this.g);this.h=qd(this);this.g.moleVersion||this.h.then(function(b){this.g.moleVersion=b.cbfVersion},function(){},this);this.g.experiments||this.h.then(function(b){this.g.experiments=b.experiments},function(){},this);this.h.then(this.i,function(){},this)}
function qd(a){return mc(a.g.alphaTestMode?"//ssl.gstatic.com/support/realtime/operatorParamsDev":a.g.stagingMode?"//ssl.gstatic.com/support/realtime/operatorParamsStaging":"//ssl.gstatic.com/support/realtime/operatorParams").then(function(b){if(!b)throw Error("operatorParams is null");return b},function(b){throw b;})}
function rd(a){var b=sd();if(b)return b;if(b=td())return a=I(b),ud(a),a;a=vd(a).then(function(c){var d={document:this.g.document};this.g.operatorDeferredUrl=c;try{return Bc(ob(c),d).then(function(){return n.cs.OperatorDeferred.getInstance(this.g)},function(e){throw e;},this)}catch(e){throw e;}},null,a);ud(a);return a}od.prototype.i=function(a){(new RegExp(a.eagerLoadHostnamePattern,a.eagerLoadHostnameFlags)).test(this.g.document.location.href)&&J(rd(this),ma(wd,"Error retrieving OperatorDeferred"))};
function vd(a){return a.g.operatorDeferredUrl?I(a.g.operatorDeferredUrl):a.g.operatorDeferredBaseUrl?(a=a.g.operatorDeferredBaseUrl+"/"+a.g.moleVersion+"/operatordeferred_bin_base__"+a.g.localeName.replace(/-/g,"_").toLowerCase()+".js",I(a)):a.h.then(v(function(b){return"https://ssl.gstatic.com/support/realtime/operator/"+b.cbfVersion+"/operatordeferred_bin_base__"+this.g.localeName.replace(/-/g,"_").toLowerCase()+".js"},a),function(b){throw b;})}
function xd(a,b){return rd(a).then(ma(function(c,d){d.registerAvailabilityCallbacks(c)},b))}function yd(a){return rd(a).then(function(b){b.getAvailabilities()})}function zd(a,b,c){b=ma(function(d,e,f,g,h,l){return l.requestSupport(d,e,f,g,h)},b,c,void 0,!0,void 0);return(c=td())?(a=b(c),I(a)):rd(a).then(b)}function td(){return p("cs.operatorDeferredInstance")}function sd(){var a=p("cs.operatorDeferredPromise");return a instanceof G?a:null!=a?I(a):null}
function ud(a){ba("cs.operatorDeferredPromise",a)}function wd(){}function pd(a){a=Ja(a);a.document=a.document||document;null!=a.localeName&&(a.localeName=a.localeName.replace(/_/g,"-"));a.localeName=a.localeName&&0<=qa(Ad,a.localeName)?a.localeName:"en";a.helpCenterName=a.helpCenterName||"chatsupport";a.apiKey=a.apiKey||"AIzaSyB5V4SIBGmrqREm7kf2fBJgPcBMCdUrLzE";return a}var Ad="ar ar-XB bg ca cs da de el en en-AU en-GB en-XA en-XC es es-419 et fa fi fil fr hi hr hu id it iw ja ko lt lv ms nl no pl pt-PT pt-BR ro ru sk sl sr sv th tr uk vi zh-CN zh-TW zh-HK".split(" ");function T(a){y.call(this);this.h=a}w(T,y);T.prototype.g=function(a){return Bd(this,a)};function U(a,b){a=Object.prototype.hasOwnProperty.call(a,ia)&&a[ia]||(a[ia]=++ja);return(b?"__wrapper_":"__protected_")+a+"__"}function Bd(a,b){var c=U(a,!0);b[c]||((b[c]=Cd(a,b))[U(a,!1)]=b);return b[c]}
function Cd(a,b){function c(){if(a.l)return b.apply(this,arguments);try{return b.apply(this,arguments)}catch(e){var d=e;if(!(d&&"object"===typeof d&&"string"===typeof d.message&&0==d.message.indexOf("Error in protected function: ")||"string"===typeof d&&0==d.indexOf("Error in protected function: ")))throw a.h(d),new Dd(d);}finally{}}c[U(a,!1)]=b;return c}
function Ed(a,b){var c=p("window"),d=c[b];c[b]=function(e,f){"string"===typeof e&&(e=ma(na,e));arguments[0]=e=Bd(a,e);if(d.apply)return d.apply(this,arguments);var g=e;if(2<arguments.length){var h=Array.prototype.slice.call(arguments,2);g=function(){e.apply(this,h)}}return d(g,f)};c[b][U(a,!1)]=d}T.prototype.w=function(){var a=p("window");var b=a.setTimeout;b=b[U(this,!1)]||b;a.setTimeout=b;b=a.setInterval;b=b[U(this,!1)]||b;a.setInterval=b;T.H.w.call(this)};
function Dd(a){x.call(this,"Error in protected function: "+(a&&a.message?String(a.message):String(a)));(a=a&&a.stack)&&"string"===typeof a&&(this.stack=a)}w(Dd,x);function Fd(a){var b=[];Gd(new Hd,a,b);return b.join("")}function Hd(){}
function Gd(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(Array.isArray(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),Gd(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),Id(d,c),c.push(":"),Gd(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":Id(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}}var Jd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Kd=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;
function Id(a,b){b.push('"',a.replace(Kd,function(c){var d=Jd[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).substr(1),Jd[c]=d);return d}),'"')};function V(a){R.call(this);this.headers=new kd;this.v=a||null;this.i=!1;this.s=this.g=null;this.F="";this.j=this.A=this.m=this.B=!1;this.M=0;this.o=null;this.R="";this.N=this.S=!1}w(V,R);var Ld=/^https?$/i,Md=["POST","PUT"],Nd=[];k=V.prototype;k.da=function(){this.O();va(Nd,this)};
function Od(a,b,c,d,e){if(a.g)throw Error("[goog.net.XhrIo] Object is active with another request="+a.F+"; newUri="+b);c=c?c.toUpperCase():"GET";a.F=b;a.B=!1;a.i=!0;a.g=a.v?a.v.g():Pb.g();a.s=a.v?Ob(a.v):Ob(Pb);a.g.onreadystatechange=v(a.W,a);try{a.A=!0,a.g.open(c,String(b),!0),a.A=!1}catch(g){Pd(a);return}b=d||"";var f=new kd(a.headers);e&&nd(e,function(g,h){f.set(h,g)});e=ta(f.C());d=n.FormData&&b instanceof n.FormData;!(0<=qa(Md,c))||e||d||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
f.forEach(function(g,h){this.g.setRequestHeader(h,g)},a);a.R&&(a.g.responseType=a.R);"withCredentials"in a.g&&a.g.withCredentials!==a.S&&(a.g.withCredentials=a.S);try{Qd(a),0<a.M&&(a.N=Rd(a.g),a.N?(a.g.timeout=a.M,a.g.ontimeout=v(a.I,a)):a.o=hd(a.I,a.M,a)),a.m=!0,a.g.send(b),a.m=!1}catch(g){Pd(a)}}function Rd(a){return C&&db(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout}function ua(a){return"content-type"==a.toLowerCase()}k.I=function(){"undefined"!=typeof aa&&this.g&&(S(this,"timeout"),this.abort(8))};
function Pd(a){a.i=!1;a.g&&(a.j=!0,a.g.abort(),a.j=!1);Sd(a);Td(a)}function Sd(a){a.B||(a.B=!0,S(a,"complete"),S(a,"error"))}k.abort=function(){this.g&&this.i&&(this.i=!1,this.j=!0,this.g.abort(),this.j=!1,S(this,"complete"),S(this,"abort"),Td(this))};k.w=function(){this.g&&(this.i&&(this.i=!1,this.j=!0,this.g.abort(),this.j=!1),Td(this,!0));V.H.w.call(this)};k.W=function(){this.l||(this.A||this.m||this.j?Ud(this):this.P())};k.P=function(){Ud(this)};
function Ud(a){if(a.i&&"undefined"!=typeof aa&&(!a.s[1]||4!=(a.g?a.g.readyState:0)||2!=Vd(a)))if(a.m&&4==(a.g?a.g.readyState:0))hd(a.W,0,a);else if(S(a,"readystatechange"),4==(a.g?a.g.readyState:0)){a.i=!1;try{var b=Vd(a),c;if(!(c=Mb(b))){var d;if(d=0===b){var e=gc(String(a.F));d=!Ld.test(e)}c=d}c?(S(a,"complete"),S(a,"success")):Sd(a)}finally{Td(a)}}}function Td(a,b){if(a.g){Qd(a);var c=a.g,d=a.s[0]?q:null;a.g=null;a.s=null;b||S(a,"ready");try{c.onreadystatechange=d}catch(e){}}}
function Qd(a){a.g&&a.N&&(a.g.ontimeout=null);a.o&&(n.clearTimeout(a.o),a.o=null)}function Vd(a){try{return 2<(a.g?a.g.readyState:0)?a.g.status:-1}catch(b){return-1}}xb(function(a){V.prototype.P=a(V.prototype.P)});function W(a,b,c){R.call(this);this.m=b||null;this.j={};this.s=Wd;this.o=a;if(!c)if(this.g=null,C&&!db("10"))qb(v(this.i,this));else{this.g=new T(v(this.i,this));Ed(this.g,"setTimeout");Ed(this.g,"setInterval");a=this.g;b=p("window");c=["requestAnimationFrame","mozRequestAnimationFrame","webkitAnimationFrame","msRequestAnimationFrame"];for(var d=0;d<c.length;d++){var e=c[d];c[d]in b&&Ed(a,e)}a=this.g;wb=!0;b=v(a.g,a);for(c=0;c<ub.length;c++)ub[c](b);vb.push(a)}}w(W,R);
function Xd(a){E.call(this,"a");this.error=a}w(Xd,E);function Wd(a,b,c,d){var e=new V;Nd.push(e);e.h.add("ready",e.da,!0,void 0,void 0);Od(e,a,b,c,d)}
W.prototype.i=function(a,b){a=a.error||a;b=b?Ja(b):{};a instanceof Error&&La(b,a.__closure__error__context__984382||{});a=rb(a);if(this.m)try{this.m(a,b)}catch(Y){}var c=a.message.substring(0,1900),d=a.stack;try{var e=lc(this.o,"script",a.fileName,"error",c,"line",a.lineNumber);a:{for(var f in this.j){var g=!1;break a}g=!0}if(!g){g=e;var h=kc(this.j);e=hc(g,h)}h={};h.trace=d;if(b)for(var l in b)h["context."+l]=b[l];var m=kc(h);this.s(e,"POST",m,this.v)}catch(Y){}try{S(this,new Xd(a,b))}catch(Y){}};
W.prototype.w=function(){var a=this.g;a&&"function"==typeof a.O&&a.O();W.H.w.call(this)};function X(a,b,c,d,e,f){var g=new W("//www.google.com/tools/feedback/jserror",void 0,!0);this.i=v(g.i,g);this.s=a;this.B=c||"en";this.v=b||!1;this.A=!!d;this.o=e;this.h=this.g=null;this.u=f}function Yd(a,b,c){if(null!=b&&null!=c){var d={};d[b]=c;J(xd(a.j,d),a.i)}}k=X.prototype;k.Y=function(a){this.g=a;Yd(this,this.g,this.l)};k.Z=function(a){this.h=a;Yd(this,this.h,this.m)};k.ma=function(a){this.l=a;Yd(this,this.g,this.l)};k.na=function(a){this.m=a;Yd(this,this.h,this.m)};
k.ka=function(a){null!=this.g&&J(zd(this.j,this.g,a),this.i)};k.la=function(a){null!=this.h&&J(zd(this.j,this.h,a),this.i)};k.aa=function(){null==this.g&&null==this.h||J(yd(this.j),this.i)};X.prototype.setChatPool=X.prototype.Y;X.prototype.setHangoutPool=X.prototype.Z;X.prototype.setChatCallback=X.prototype.ma;X.prototype.setHangoutCallback=X.prototype.na;X.prototype.requestChatSupport=X.prototype.ka;X.prototype.requestHangoutSupport=X.prototype.la;X.prototype.getAvailabilities=X.prototype.aa;function Zd(){};function $d(){}w($d,Zd);function Z(a){this.g=a}w(Z,$d);Z.prototype.set=function(a,b){try{this.g.setItem(a,b)}catch(c){if(0==this.g.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};Z.prototype.get=function(a){a=this.g.getItem(a);if("string"!==typeof a&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};function ae(a){a.g.removeItem("GOOGLE_HELP_SESSION_STATE")}
Z.prototype.T=function(a){var b=0,c=this.g,d=new jd;d.next=function(){if(b>=c.length)throw id;var e=c.key(b++);if(a)return e;e=c.getItem(e);if("string"!==typeof e)throw"Storage mechanism: Invalid value was encountered";return e};return d};Z.prototype.key=function(a){return this.g.key(a)};function be(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.g=a}w(be,Z);function ce(){this.g=new be}w(ce,y);function de(a,b){var c=a.serverUri||"//www.gstatic.com/feedback";n.GOOGLE_HELP_SESSION_ARGUMENTS=arguments;var d=D(document,"SCRIPT");c=ob(c+"/session_load.js");Pa(d,c);window.document.body.appendChild(d)}ba("userfeedback.api.help.resumeOpenHelpSession",de);(function(a,b){var c=a.helpCenterPath,d=a.locale,e=a.authuser,f=a.escalationJSONString,g=!!a.useStagingServer,h=a.apiKey;var l=document.body;a:{var m=9==l.nodeType?l:l.ownerDocument||l.document;if(m.defaultView&&m.defaultView.getComputedStyle&&(m=m.defaultView.getComputedStyle(l,null))){m=m.direction||m.getPropertyValue("direction")||"";break a}m=""}l="rtl"==(m||(l.currentStyle?l.currentStyle.direction:null)||l.style&&l.style.direction);m=window;try{var Y=null==m||null==m.top||null==m.top.document}catch(Rc){Y=
!0}if(Y||window.top.GOOGLE_HELP_CHAT_SUPPORT)c=null;else{c=new X(c,l,d,g,e,h);window.top.GOOGLE_HELP_CHAT_SUPPORT=c;d={helpCenterName:c.s,localeName:c.B,source:1,rosterId:"roster-for-Google-Help",isRtl:c.v,alphaTestMode:!1,stagingMode:c.A,timeoutMs:2E4,authUser:c.o,apiKey:c.u};e=kb("DIV",{id:"roster-for-Google-Help",style:"display: none"});window.top.document.body.appendChild(e);try{c.j=new od(d)}catch(Rc){c.i(Rc)}}d=new ce;f&&(ae(d.g),f={ea:JSON.parse(f).ea},f.sessionTimestamp=(new Date).getTime(),
d.g.set("GOOGLE_HELP_SESSION_STATE",Fd(f)));if(f=d.g.get("GOOGLE_HELP_SESSION_STATE")){if(f=JSON.parse(f),e=(new Date).getTime(),g=f.sessionTimestamp,!g||"number"!==typeof g||e>g+6E4)ae(d.g),f=null}else f=null;d=(f||{}).escalationOptions;c&&d&&(f=d.hangout||{},(d=(d.chat||{}).chat_pool_id)&&c.Y(d),(f=f.hangout_pool_id)&&c.Z(f),c.aa());de(a,b)}).apply(n,n.GOOGLE_HELP_CHAT_ARGUMENTS);}).call(this);
